### ISSUE TITLE
Refresh issue on COH Tablets

### ISSUE THREAD

**Issue by pfsj** [jthrilly/netCanvas#102]
I wasn't able to replicate the bug at COH. However, by replacing the User/Username/AppData/Local/netCanvas folder with a previously "corrupted" one I could see the issue first hand. First thing to note is the top error in the first picture (i.e., cordova.js "File not found" error) appears no matter what (with a fresh install or not) and also appears on my laptop so that seems unrelated to the current issue. Second, no error appears when you try and click "Continue" to refresh the session. That is, the two errors shown in the second picture appear before you even get to the "refresh session" button. Rather, the console just reads "ioInterface being asked to delete document" every time you click the "continue" button, as shown in the third picture below. Let me know if you have questions.

Thanks!

![page1](https://cloud.githubusercontent.com/assets/10948594/9507686/7a5b9484-4c15-11e5-931a-6760e0350359.png)
![page2-2](https://cloud.githubusercontent.com/assets/10948594/9507817/3fe6732c-4c16-11e5-8431-693a1197b033.png)
![page2](https://cloud.githubusercontent.com/assets/10948594/9507825/5015a4a2-4c16-11e5-8e1b-2cde6176c040.png)

**Comment by jthrilly** [comment]
Thanks for the very detailed update Pat!

So it looks like a few things are happening here.

First of all, the missing cordova.js file isn't an error per-se. That file is generated automatically when the app is run on a mobile platform, and isn't needed when run either in a browser or inside node webkit. 

The quota error is however more serious. The database library should detect when it is running in node webkit, and use direct access to the filesystem rather than the webkit local storage API. This should mean that it can store as much data as it wants (there should be no quota). That message indicates it is incorrectly assuming it is running inside a browser.

Once the quota error has happened, the IOInterface module won't be able to recover, which is why nothing happens in the third screenshot.

The good news is that this is not a data-loss bug. 

Is there any way you can send me the corrupt data folder so that I can fix this issue?

**Comment by jthrilly** [comment]
It just occured to me that this could be happening because the interviewers are not purging the database inbetween interviews. Perhaps the terminology ('reset' vs 'purge') needs to be changed because it is confusing.

**Comment by pfsj** [comment]
Would uploading a corrupt data folder onto our shared drive somewhere where you have access to work?

As for purging the database, I believe this issue also prevents them from successfully doing that as well (i.e., The program does not response to pressing the continue button for purge confirmation box).

**Comment by jthrilly** [comment]
Of course, but what I mean is that if the data isn't purged between interviews it will build up and eventually exceed the quota (which is the bug we are experiencing). 

Yeah let me know the shared drive location and I'll fetch it from there. Should be able to fix it this afternoon.

Thanks Pat!

**Comment by pfsj** [comment]
Gotcha. I'm going to run by there this morning and move one of the folders and will let you know where I put it. I've been trying to do occasional purges myself but its possible that those have not been frequent enough. 

I'll also talk to our staff to see if the issue has re-occurred since manually purging the folder. If that is the problem, it's unlikely to have already happened again. This would also explain why we can't replicate the problem on our systems.

**Comment by pfsj** [comment]
Unfortunately, the corrupted database files are no longer on the COH computers since I gave them instructions to manually "purge" the database files by deleting them and someone must have emptied the recycling bin for the computer that I had grabbed the corrupted file from. 

I'm very much guessing the lack of purging was culprit for this bug given that the number of interviews has picked up considerably in the last two weeks (which would make more data accumulate in the local database). I'm going to take a more active role in purging them as frequently as possible. There aren't any interviewers at the center right now so I can't confirm there hasn't been in a replication of the bug on a computer that was freshly purged but, given that you and I can't replicate it, I'm guessing that is the case.

Let me know if you have any other thoughts.

**Comment by jthrilly** [comment]
Okay Pat thanks for the update.

My concern now is that if the interviewers haven't been purging the database, there's a small chance that the data might have been compromised. It might be worth checking that nothing looks different about the most recent data. 

In the mean time I will investigate the quota limit and apply a fix.

**Comment by pfsj** [comment]
We do some weekly data checks on number of partners by edge type and things like that and we haven't noticed any abnormalities. However, I'm still working on the code for cleaning the files and building the database to account for visit 2 files (and the slight modifications to the jsons for the newest builds of netCanvas-R) so I haven't systematically checked the most recent data. However, just looking through them manually, everything appears to be in order.
