### ISSUE TITLE
Categorical bins move "resting" location

### ISSUE THREAD

**Issue by pfsj** [jthrilly/netCanvas#104]
Categorical bin "resting" locations move if participants try to move too quickly from inside a categorical bin (to see which nodes are in them) and then click outside or select another category. This bug can be replicated by rapidly "opening" a category and then quickly clicking outside the bin to close it and then clicking on another category to open it. Let me know if you have questions

![catbin](https://cloud.githubusercontent.com/assets/10948594/9670319/8ca932e4-5251-11e5-9ab7-510a06ada1bd.png)

**Comment by pfsj** [comment]
Forget to mention, this issue is fixed by going back or forward and returning to the page.

**Comment by jthrilly** [comment]
I'm actually not able to reproduce this, no matter how fast I try to click to close! I wonder if it could be performance related (the animation takes longer on your lab machines which allows things to get stuck).

**Comment by jthrilly** [comment]
I've added a simple check to see if a animation is currently running. This will disable fast consecutive interactions.
