### ISSUE TITLE
Need to unset value for followup variable when the node is removed from the followup trigger group

### ISSUE THREAD

**Issue by jthrilly** [jthrilly/netCanvas#14]
Right now a node can be removed from a group that triggered a followup question (for example "Please specify gender identity: Not listed") but this will not remove any answer provided in the followup prompt. 

This can lead to a situation where the dyad edge between node and ego lists gender_p_t0: "Male" and gender_p_other: "Something else".

**Comment by jthrilly** [comment]
Asked Pat for list of steps with follows for testing.

**Comment by pfsj** [comment]
The list of these questions/options that launch popups can be found here: https://docs.google.com/spreadsheets/d/1KGQJGh4_Fh93UD-B0j3Pk__cIC292D-hiM7L47j-UA4/edit?usp=sharing
