### ISSUE TITLE
Formatting of drug names needs to be changed

### ISSUE THREAD

**Issue by glp2** [jthrilly/netCanvas#27]
{label:'LIST SELECT: which drugs?', page:'listselect1.html'},

Formatting of the drug names should be changed so that the name (e.g., marijuana) is larger on top of the button, with the slang names displayed smaller below and italicized rather than in quotes.
<div class=”form-group list-container”>
<div class="item" data-nodeid=”d1_t0” style=”border: 2px solid red; background: rgb(232, 192, 192);”>
    <h3>
        <strong>Marijuana (“Weed”, “Pot”)</strong>
    </h3>
</div>
...
</div>
<script>
        …
        variables: [
            {label: ‘Marijuana (“Weed”, “Pot”)’,value: ‘d1_t0’},
            …
        ],
        …
    </script>

**Comment by jthrilly** [comment]
Aesthetics are fine, but I will revise the way this is stored.

**Comment by jthrilly** [comment]
Seems fine.
