### ISSUE TITLE
Ego's name and gender need to be added

### ISSUE THREAD

**Issue by glp2** [jthrilly/netCanvas#30]
{label:'Intro', page:'intro.html'},

Two new variables need to be created after the following step: ego_name and ego_gender (see code)

These variables will collect the participant’s first name and their gender.  The first name will be used on the final screen “Thank you XXX.”  The gender will be used for logic checks for which sex questions are asked.

**Comment by jthrilly** [comment]
We need to know how the questions will be phrase specifically. I would also like variable names, please!

**Comment by glp2** [comment]
The variable name/options are currently in the Network Data Manual on Box.  Here's what we would like to see:

- "Participant's gender identity:" <drop-down box with four options>
     - Male, Female, Transgender: Female to Male, Transgender: Male to Female

The variable should be named GENDER_K.

**Comment by glp2** [comment]
We've actually realized that we shouldn't be collecting the participant's name on the first screen.  We tell them that their name will never be connected to their study ID, and then we collect both on the first screen of the first interview they take.  This needs to be removed.
