### ISSUE TITLE
Make all screens consistent with using "6" instead of "six"

### ISSUE THREAD

**Issue by glp2** [jthrilly/netCanvas#32]
{label:'NET: layout and social', page:'canvasedge1.html'}
{label:'NET NI: who drunk with', page:'canvasselect3.html'}
{label:'NET NI: who drugs with', page:'canvasselect4.html'}
{label:'NET NI: who sex with', page:'canvasselect5.html'}
{label:'CAT: Vaginal sex?', page:'multibin9.html'}
{label:'CAT: Anal sex?', page:'multibin10.html'}

**Comment by jthrilly** [comment]
Go with the number 6.
