### ISSUE TITLE
Text for "specify venue" pop-up needs to be editted

### ISSUE THREAD

**Issue by glp2** [jthrilly/netCanvas#41]
{label:'CAT: where met sex partners', page:'multibin6.html'}

- In the pop-up screen, can the text be changed so that it’s different depending on the category?  For instance, if a partner is dragged into the “Bar/Club” bin, the participant should be given the prompt “Please provide the name of the bar or club.”  And if they are dropped in the “Online/Mobile App” bin, the participant should be prompted with “Please provide the name of the website or mobile app.”
<!script>
        …
        questions: [
            {
prompt: ‘Please provide further details of the name of the venue/website/app.’,
                variable:’loc_met_detail_t0’
            }
        ]
        ...
    <!/script>

**Comment by jthrilly** [comment]
Please provide the name of the venue/website/app where you met them.
