### ISSUE TITLE
Only show vaginal sex questions when appropriate

### ISSUE THREAD

**Issue by glp2** [jthrilly/netCanvas#43]
{label:'CAT: Vaginal sex?', page:'multibin9.html'}
- This screen should only pop up if the participant identifies as a gender other than male OR the participant identifies at least one sexual partner who is not male.  Additionally, male-male sexual partnerings should not appear on this screen.

**Comment by jthrilly** [comment]
Related to #30

**Comment by glp2** [comment]
We'd like for the sex questions to be as inclusive as possible.  So, we would like the following logic implemented for the anal/vaginal sex questions:

- the above statement for vaginal sex is correct: any sexual pairings except male-male should appear on this screen
- for anal sex, any sexual pairings except female-female should appear on this screen

**Comment by glp2** [comment]
The vaginal sex questions should also not appear for female-female sexual pairings.
