### ISSUE TITLE
"More than 6 months ago" button

### ISSUE THREAD

**Issue by glp2** [jthrilly/netCanvas#44]
{label:'DATE: first and last sex', page:'dateinterface1.html'}
- We aren’t interested in sexual encounters that occurred more than six months ago.  Can we add a button under “When was the first time you had sex?” that says “More than 6 months ago”?  And is it possible to provide the date for six months ago?

**Comment by jthrilly** [comment]
Store with two variables:
Binary variable: first sex within 6 months: yes/no
Date variable: date if present, missing if skipped (and binary variable flipped)

**Comment by glp2** [comment]
Need to remove "more than 6 months ago" as an option for the last time they had sex.  Participants should only indicate partners within the last 6 months, so no one should be marking that the last sexual encounter was greater than 6 months ago.
