### ISSUE TITLE
"Not listed" option for recruiter

### ISSUE THREAD

**Issue by glp2** [jthrilly/netCanvas#57]
{label:'NET NI: who recruited', page:'canvasselect2.html'}
- This screen should not appear for participants who indicated they were a “seed” on the first screen.
There should be a “Not Listed” button in case the participant’s recruiter isn’t listed in their network.

**Comment by jthrilly** [comment]
I've rephrased the prompt to "If they are present in your network, please tap on the person who recruited you into this study. If they are not present, click the next arrow."

The skip logic was already implemented.

**Comment by glp2** [comment]
We'd still prefer there to be a button that participants can tap on to indicate "Not Listed."  This also doesn't match with our interviewer guide, in which we ask the participant if they want to go back and add the recruiter in one of the name generator steps.

**Comment by jthrilly** [comment]
I'm a little confused. You say it doesn't match the interview guide...but wouldn't this be more in keeping with the interview guide? As in, if you haven't put them in when prompted (and you haven't gone back and added them) you don't want them there, and so can click next. 

The other way of looking at is that, programmatically speaking, the 'not listed' button will just trigger the next button. Though I can obviously do that, it does seem redundant.

 I don't think the data structure can support storing the absence of an edge, and I wouldn't recommend storing a null or undefined variable value.

**Comment by jthrilly** [comment]
@berniehogan: could use your input here.

**Comment by glp2** [comment]
Our big concern is just that we don't want people to tap on the right arrow as a surrogate for "no."  Since this is important for matching, we want to make sure people don't forget this step or tap on the arrow accidentally.

Maybe this is something to discuss on Friday?

**Comment by jthrilly** [comment]
Okay agreed. I can do the change quite quickly – I just wanted to make it
closed so I could satisfy my OCD ;)
