### ISSUE TITLE
Multiple edge types not shown on Sociogram

### ISSUE THREAD

**Issue by wwqrd** [jthrilly/netCanvas#672]
We have the option to display multiple edge types on Sociogram, however, if two nodes are connected by multiple edge types, this isn't visible on Sociogram. Brown and Braun are connected by both edge types, but only one is visible:

<img width="742" alt="2 edges not displayed" src="https://user-images.githubusercontent.com/776599/45424582-d762fc80-b68e-11e8-9f78-cf9ca60f8bcd.png">

**Comment by jthrilly** [comment]
This is by design, although we might improve the transparency of the feature.

The idea is that there is an edge "precedence", and the higher precedence edge is the one that is rendered.

**Comment by rebeccamadsen** [comment]
Out of curiosity, does adding a second edge between the same two nodes actually create two edges in the redux network, or does the existing edge get updated? Where is edge precedence set?

**Comment by jthrilly** [comment]
> Out of curiosity, does adding a second edge between the same two nodes actually create two edges in the redux network, or does the existing edge get updated? Where is edge precedence set?

Adding another edge does create another edge in the redux network, yes. Although Gephi flattens these when importing a graphML (which is an unrelated gephi limitation).

Each prompt can only create a single edge type, whereas it can display any number. The precedence is set in the ordering of the edges to display in the prompt configuration.
