### ISSUE TITLE
Map zooming removes details

### ISSUE THREAD

**Issue by glp2** [jthrilly/netCanvas#74]
If you zoom in to the final map layer, all of the details disappear.  I've recorded what happens and will send it for visual confirmation of the problem.

**Comment by jthrilly** [comment]
Did we ever get verification that this is fixed with proper install procedure and the latest tiles?

**Comment by glp2** [comment]
It still wasn't working as of Friday when I uninstalled and reinstalled everything (including the tiles file).

**Comment by jthrilly** [comment]
When you say 'wasn't working' what do you mean exactly? No tiles at all, or no tiles at the smallest zoom level?

Do you have any debug information from the console I could see?

**Comment by glp2** [comment]
It's only at the smallest level - everything still looks good one level up.  I remembered to check it, but was still too out of it to get any more information from the computer on Friday.  If there's anything specific that would be helpful, let me know and I'll see if we can get it for you.
