### ISSUE TITLE
List of last sex partners

### ISSUE THREAD

**Issue by glp2** [jthrilly/netCanvas#77]
In a practice interview yesterday, a participant indicated having sex with two people, but said that it wasn't vaginal or anal.  However, these two people showed up on the final screen in the list of last sex partners.  We only want vaginal and anal sex partners to appear on this screen - not oral sex partners. 

Additionally, what would happen on that screen if the participant didn't provide dates for some of his sex partners?  Would those partners still show up on the screen if the participant had 5 or fewer vaginal/anal sex partners?

**Comment by jthrilly** [comment]
Currently, those sex partners without dates do not show up at all. How would you like them to be integrated in the context of others potentially having dates?

**Comment by glp2** [comment]
Ideally, we would like for sex partners without dates to show up at the end of the list, provided there are still open slots.
