### ISSUE TITLE
Changing drug selection removes all drugs previously selected

### ISSUE THREAD

**Issue by pfsj** [jthrilly/netCanvas#80]
After selecting multiple drugs and then returning to the page "LIST SELECT: which drugs?" to deselect a single drug, the subsequent json file has ALL drugs removed instead of only the drug that was deselected.

For example, if I complete the following steps the subsequent json dowload does not indicate ANY drugs being selected.

1) On the "LISTS SELECT: which drugs?' page, select "Marijuana", "Cocaine or Crack", and "Heroin"
2) Click to the right arrow to go to the next page
3) Click the left arrow to return to the "LIST SELECT: which drugs?" page
4) Click "Cocaine or Crack" to deselect that drug
5) Click the right arrow and download data immediately or after completing the rest of the survey

**Comment by jthrilly** [comment]
This has been fixed now, but the solution changes the data structure a bit.

Previously all dn_t0 values would be set to undefined if not selected, but now the values will not be present at all unless either:

1) They are selected. In this case they will be given the value 1.
2) They had previously been selected, but then have been deselected. In this case they will have the value 0.

Though not ideal, this will maintain the queryability of the data (we just need to be careful to select for values that are either 0 OR undefined when we want to exclude specific drugs). It saves implementing a method to delete keys and/or storing this information on some sort of special edge.
