### ISSUE TITLE
Json download file not automatically named after session ID

### ISSUE THREAD

**Issue by pfsj** [jthrilly/netCanvas#81]
When downloading data, the json file is not automatically named after the session ID as it was in previous versions.

**Comment by jthrilly** [comment]
This was deliberate. Session IDs are not guaranteed to be unique, and this way requires that the user think about the naming system. Also: there should be a naming policy in place for these files. If you have one, I could perhaps implement that instead of the session ID

**Comment by jthrilly** [comment]
name files sessionid_timestamp
