### ISSUE TITLE
Can we move Reset Session and Purge Database further from Download Data

### ISSUE THREAD

**Issue by pfsj** [jthrilly/netCanvas#82]
Is it possible to move "reset session" and "purge database" further away on the screen from "download data" given that the touchscreen interfaces we have make it relatively easy to unintentional press a button? For example, moving "Download Data" up and introducing blank space between it and the reset session/purge database buttons which could be placed lower on the menu would likely be an excellent safety measure.

**Comment by jthrilly** [comment]
This is not currently possible. Instead, I will implement a confirmation dialog for destructive changes and make the spacing bigger.
