### ISSUE TITLE
Pop-up questions

### ISSUE THREAD

**Issue by glp2** [jthrilly/netCanvas#83]
There are major issues with all of the survey questions in RC4 that have pop-up windows.  Specifically, when you place someone in a bin that requires a follow-up question, multiple pop-up windows appear rather than just one.  

Pat will be sending screenshots via email for clarification of the exact problem.

**Comment by jthrilly** [comment]
Woops! Hopefully a quick fix.

**Comment by pfsj** [comment]
In addition to the multiple pop-up windows appearing, when you complete the front popup window by inputting data and pressing "continue", the next time the same pop-up appears (e.g., if you drag another alter into the bin) the pop-up window has the previous alter's data in it. Here are a couple of screenshots of the issue generally. 

![netcanvas_error](https://cloud.githubusercontent.com/assets/10948594/6375651/2aaf9faa-bcde-11e4-83eb-75824b8be082.png)

![netcanvas_error2](https://cloud.githubusercontent.com/assets/10948594/6375655/31ecca40-bcde-11e4-9bb7-14f8b7786084.png)

**Comment by jthrilly** [comment]
Thanks guys. I've fixed it. My network is down but I'll upload fresh builds
in a matter of minutes.
