### ISSUE TITLE
int_date_t0 is incorrect

### ISSUE THREAD

**Issue by pfsj** [jthrilly/netCanvas#85]
int_date_t0 is one day ahead of the actual date of the interview.

**Comment by jthrilly** [comment]
Are you sure it isn't in British date format? i.e today is 3/3/2015, but tomorrow is 4/3/2015 for me and 3/4/2015 for you.

**Comment by pfsj** [comment]
Pretty certain it is stamping it one day ahead. It's actually inverted British date format (year/month/day). For example, last Thursday we had our first participant on 2015/2/26 but the "int_date_t0" stamp says 2015/2/27.

**Comment by jthrilly** [comment]
You're absolutely right Pat.

getUTCMonth() starts at 0 in Javascript but getUTCDate() starts at 1, which is fabulously helpful.

**Comment by jthrilly** [comment]
Do you need a new build for this?

**Comment by glp2** [comment]
That would be ideal :)

**Comment by jthrilly** [comment]
Compiled :) https://github.com/jthrilly/netCanvas/releases :+1:

**Comment by glp2** [comment]
Awesome - thank you!
