### ISSUE TITLE
Logic for vaginal sex question

### ISSUE THREAD

**Issue by pfsj** [jthrilly/netCanvas#88]
We'd like to adjust the logic behind the vaginal sex question so it is shown for all sex partners other than pairs that identify as Male-Male and Female-Female (i.e., as indicated in variables "gender_k" and gender_p_tx*).

**Comment by jthrilly** [comment]
Just to be clear, the current logic is to only skip male male. You now want to add female female?

**Comment by jthrilly** [comment]
Actually, the current logic is to skip male participants with only male sex partners, or female participants with only female sex partners.

**Comment by jthrilly** [comment]
I'll wait for this info before doing another build that fixes this and #89.

**Comment by pfsj** [comment]
Sorry, I should have been more clear. Our concern is regarding how trans participants are handled with this logic. Specifically, a MTF trans participant was not prompted about vaginal sex with her female partner. We only want this question suppressed if both participant and partner are cisgender in a male-male or female-female dyad.

**Comment by jthrilly** [comment]
I still don't understand how this isn't covered by the logic we have. We ONLY skip if its a male participant with only male partners or its a female participant with only female partners.

Any non-cisgendered combination should cause this question not to be skipped.

This is the current logic

``` javascript
if ((egoGender === 'Male' && totalEdges.length === maleEdges.length) || (egoGender === 'Female' && totalEdges.length === femaleEdges.length)) { 
// skip 
else {
// don't skip
}
```

**Comment by glp2** [comment]
Hmm...any other thoughts on why an MTF participant with a female sex partner would get the anal sex question but not the vaginal sex one?

**Comment by jthrilly** [comment]
I've just checked now, and there is a problem but it is with the actual interface (i.e multibin9.html). The vaginal sex question will show up for a MTF participant with a female partner, but the partner won't show up to be dragged into a bin. However, they *will* show up to be dragged into a bin in the anal sex question. Fixing now.

**Comment by jthrilly** [comment]
Okay fixed, but I would appreciate some further testing. Uploading new builds now.
