### ISSUE TITLE
Serious partner name at end of survey

### ISSUE THREAD

**Issue by pfsj** [jthrilly/netCanvas#90]
We've had a report that a serious partner did not appear on the final screen that prints sexual partners and serious partners. I have not been able to replicate this issue. However, we wanted to put it on here in case you had any thoughts why this might happen.

**Comment by jthrilly** [comment]
Thanks for the report pat. Are you not able to verify by examining the
study JSON output?

**Comment by pfsj** [comment]
On the JSON, there is an alter that is indicated as a serious partner but neither Gregory nor I could find any irregularities in the JSON. The interviewer thought it might be because the participant did not report sex with that alter (or any other alter). However, I've run a number of test cases through NetCanvas with that scenario and it has still printed the serious partner every time.

**Comment by jthrilly** [comment]
If I implement a method to load a JSON back into the app, would you be able
to verify the bug?

**Comment by pfsj** [comment]
Unless it would be extremely easy and quick to implement, we don't think it's really worth the trouble of building that functionality given how minor this issue is.

**Comment by jthrilly** [comment]
Okay. I'll probably implement the feature in the future anyway, and this
will need to be verified against the 2.x branch then. If you could just
make a note of the case so that we can go back to this then, that would be
perfect.

I'm assuming no news is good news re: my email btw! Hope you guys are cool
with everything.
